"""Compatibility wrapper for STAR*NET ``.dat`` observation records.

Current/native records use ``direction distance zenith``. Older files emitted by
this BTM mock-up used ``direction zenith distance`` and always included either a
``# raw:...`` trace comment or the three legacy weight columns. The wrapper
normalises only records carrying those unambiguous legacy markers, then delegates
to the strict native parser.
"""

from __future__ import annotations

import re
from typing import Any

from .parsers import parse_dat as _parse_dat_native

_FLOAT_RE = re.compile(r"^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][+-]?\d+)?$")


def _is_number(value: str) -> bool:
    return bool(_FLOAT_RE.fullmatch(value))


def _is_legacy_dm(parts: list[str], inline_comment: str, *, has_scale: bool) -> bool:
    """Return true only when the old BTM field order is identifiable safely."""
    if len(parts) < 5 or not all(_is_number(value) for value in parts[2:5]):
        return False

    # Every record generated by the previous builder included this audit marker.
    if re.search(r"\braw\s*:", inline_comment, re.IGNORECASE):
        return True

    # Old records with per-observation weights have:
    # DM target direction zenith distance sigmaDir sigmaZen sigmaDist HI HT
    if len(parts) >= 10:
        return True

    # A final conservative fallback: zenith angles cannot exceed 180 degrees.
    # This identifies legacy records with a long distance while avoiding guesses
    # when all three values are physically plausible in either order.
    if len(parts) >= 7 and not has_scale and "/" not in parts[-1]:
        second = float(parts[3])
        third = float(parts[4])
        if 0.0 <= second <= 180.0 and abs(third) > 180.0:
            return True

    return False


def _normalise_legacy_dm_order(content: str) -> str:
    lines = content.splitlines()
    has_scale = any(line.strip().upper().startswith(".SCALE") for line in lines)
    normalised: list[str] = []

    for raw in lines:
        data, separator, comment = raw.partition("#")
        stripped = data.strip()
        if not stripped.upper().startswith("DM "):
            normalised.append(raw)
            continue

        parts = stripped.split()
        if _is_legacy_dm(parts, comment.strip(), has_scale=has_scale):
            # Old: DM target direction zenith distance ...
            # New: DM target direction distance zenith ...
            parts[3], parts[4] = parts[4], parts[3]
            indentation = data[: len(data) - len(data.lstrip())]
            rebuilt = indentation + " ".join(parts)
            if separator:
                rebuilt += "  # " + comment.strip()
            normalised.append(rebuilt)
        else:
            normalised.append(raw)

    result = "\n".join(normalised)
    if content.endswith(("\n", "\r")):
        result += "\n"
    return result


def parse_dat(content: str) -> dict[str, Any]:
    """Parse native and legacy BTM ``.dat`` records without silent field swaps."""
    return _parse_dat_native(_normalise_legacy_dm_order(content))
