"""Build the STAR*NET project file (``.prj`` / ``.snproj`` key subset)."""

from __future__ import annotations

from typing import Any


def build_prj(*, adjustment: dict[str, Any], run_label: str) -> str:
    auto = adjustment.get("auto_adjust", {})
    lines = [
        "# STAR*NET project — generated by BTM Topographic Adjustment",
        f"RUN_LABEL {run_label}",
        f"DIMENSION {adjustment.get('dimension', '3D')}",
        f"UNITS_LINEAR {adjustment.get('units_linear', 'M')}",
        f"UNITS_ANGULAR {adjustment.get('units_angular', 'DEG')}",
        f"COORD_SYSTEM {adjustment.get('system', 'LOCAL')}",
        f"COORD_ORDER {adjustment.get('coordinate_order', 'ENH')}",
        f"CONVERGENCE_THRESHOLD_M {float(adjustment.get('convergence_threshold_m', 1e-6)):.2E}",
        f"MAX_ITERATIONS {int(adjustment.get('max_iterations', 20))}",
        f"CHI2_SIGNIFICANCE {float(adjustment.get('chi_square_significance', 0.05)):.3f}",
        f"CONFIDENCE_LEVEL {float(adjustment.get('confidence_level', 0.95)):.3f}",
        f"ERROR_PROPAGATION {'ON' if adjustment.get('error_propagation', True) else 'OFF'}",
        "# SCALE, atmospheric and prism corrections are resolved upstream by BTM;",
        "# STAR*NET receives final corrected slope distances — never correct twice.",
        "SCALE_FACTOR 1.0",
        "REFRACTION_COEFFICIENT " + f"{float(adjustment.get('refraction_coefficient', 0.14)):.3f}",
        f"AUTO_ADJUST {'ON' if auto.get('enabled') else 'OFF'}",
        f"AUTO_ADJUST_MAX_ITERATIONS {int(auto.get('max_iterations', 5))}",
        f"AUTO_ADJUST_MAX_STD_RESIDUAL {float(auto.get('max_standardized_residual', 3.0)):.2f}",
    ]
    return "\n".join(lines) + "\n"
