"""Build native STAR*NET `.prj` / `.snproj` project settings."""

from __future__ import annotations

from typing import Any


def _percent(value: Any, default: float) -> float:
    number = float(default if value is None else value)
    return number * 100.0 if 0.0 <= number <= 1.0 else number


def _linear_units(value: Any) -> str:
    token = str(value or "Meters").strip().lower()
    return {
        "m": "Meters",
        "meter": "Meters",
        "meters": "Meters",
        "metres": "Meters",
        "ft": "Feet",
        "feet": "Feet",
        "feet-us": "FeetUS",
        "feetus": "FeetUS",
    }.get(token, str(value or "Meters"))


def build_prj(*, adjustment: dict[str, Any], run_label: str) -> str:
    """Generate the stable native subset shared by STAR*NET 6 and 14.

    A production worker can merge this deterministic section set into an
    approved licensed project template when additional UI-only settings are
    required.
    """
    format_version = int(adjustment.get("starnet_project_format_version", 3))
    software_version = str(adjustment.get("starnet_software_version", "BTM-generated"))
    dimension = str(adjustment.get("dimension", "3D")).upper()
    coord_order = str(adjustment.get("coordinate_order", "ENH")).upper()
    coord_order = "NE" if coord_order.startswith("NE") else "EN"
    significance = _percent(adjustment.get("chi_square_significance"), 0.05)
    confidence = _percent(adjustment.get("confidence_level"), 0.95)
    refraction = float(adjustment.get("refraction_coefficient", 0.07))
    scale = float(adjustment.get("scale_factor", 1.0))

    lines = [
        f"*STAR*NET {format_version}",
        "#",
        f"# {software_version}",
        f"# RUN_LABEL {run_label}",
        "# SCALE_FACTOR 1.0",
        "# Generated by BTM Topographic Adjustment.",
        "# Prism and atmospheric corrections are resolved upstream; SCALE remains explicit.",
        "#",
        "[Adjustment]",
        "#",
        f"adjustment_type                {dimension}",
        f"linear_units                   {_linear_units(adjustment.get('units_linear'))}",
        f"angle_output_units             {str(adjustment.get('units_angular', 'DMS')).upper()}",
        f"local_or_grid_adjustment       {int(adjustment.get('local_or_grid_adjustment', 0))}",
        f"coordinate_projection          {int(adjustment.get('coordinate_projection', 0))}",
        f"coordinate_zone                {int(adjustment.get('coordinate_zone', 0))}",
        f"scale_factor                   {scale:.10f}",
        f"coordinate_order               {coord_order}",
        "coordinate_order_north         N",
        f"angle_station_order            {adjustment.get('angle_station_order', 'At-From-To')}",
        f"3D_input_mode                  {adjustment.get('input_3d_mode', 'Slope/Zenith')}",
        f"index_of_refraction            {refraction:.10f}",
        f"earth_radius_meters            {float(adjustment.get('earth_radius_meters', 6372000.0)):.10f}",
        f"converge_limit                 {float(adjustment.get('convergence_threshold_m', 1e-6)):.10f}",
        f"maximum_iterations             {int(adjustment.get('max_iterations', 20))}",
        f"chi_sqr_percent_significance   {significance:.4f}",
        f"perform_error_propagation      {1 if adjustment.get('error_propagation', True) else 0}",
        f"ell_percent_confidence         {confidence:.4f}",
        "#",
        "[Listing]",
        "#",
        "print_input_file               0",
        "list_observations              1",
        "list_sideshot_observations     1",
        "list_adj_obs_residuals         1",
        "list_adj_dist_az               1",
        "list_converge                  1",
        "list_coordinates               1",
        "show_coord_changes             1",
        "coord_changes_from_entered     1",
        "list_standard_deviations       1",
        "list_station_ellipses          1",
        "list_relative_ellipses         1",
        "create_coordinate_file         1",
        "coordinate_output_script       Default",
        "number_coord_decimals          5",
        "number_elevation_decimals      5",
        "#",
        "[Instrument]",
        "#",
        f"distance_constant              {float(adjustment.get('distance_constant_m', 0.001)):.10f}",
        f"distance_ppm                   {float(adjustment.get('distance_ppm', 1.0)):.10f}",
        f"direction_seconds              {float(adjustment.get('direction_arcsec', 2.5)):.10f}",
        f"zenith_seconds                 {float(adjustment.get('zenith_arcsec', 1.5)):.10f}",
        "##################################################",
        "########",
    ]
    return "\n".join(lines) + "\n"
